a = input('digite algo: ')
print('O tipo primitivo desse valor e ', type(a))
print('So tem espacos?', a.isspace())
print('E um numero?', a.isnumeric())
print('E alfabetico?', a.isalpha())
print('E alfanumerico?', a.isalnum())
print('Esta em maiusculo?', a.isupper())
print('Esta em minusculo?', a.islower())
print('Esta capitalizado?', a.istitle())
